### ISSUE TITLE
Intégrer un algo de création de la structure en base

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#1]
A partir de https://raw.githubusercontent.com/3liz/lizmap-adresse-module/master/adresse/install/sql/adresse.sql ajouter les algos de création de la structure de base de données

- [x] Ajouter les scripts de création de la documentation SchemaSpy 2ac6d8c
- [x] Ajouter les scripts de création des fichiers SQL d'installation 27b4a82
- [x] Ajouter l'algorithme de création de la structure
- [x] Ajouter l'algotithme de mise à jour de la structure

**Comment by mdouchin** [comment]
@drillinP @rldhont

**Comment by rldhont** [comment]
@mdouchin merci

**Comment by Gustry** [comment]
Just to keep note : `getVersionInteger` is not defined in the code
