### ISSUE TITLE
Problème de récupération des URI sur certains algo processing

### ISSUE THREAD

**Issue by drillinP** [3liz/qgis-gestion_base_adresse-plugin#102]
Utiliser `from ...qgis_plugin_tools.tools.database import get_uri_from_connection_name`
à la place de [`from processing.tools.postgis import uri_from_name` ](https://github.com/3liz/qgis-gestion_base_adresse-plugin/blob/master/gestion_base_adresse/processing/data/data_parcelle.py#L15) ?

Erreur retournée au lancement de QGIS : `No module named 'processing.tools.postgis' `

**Comment by Gustry** [comment]
C'est le travail #66.
Prendre exemple sur PgMetadata.
Il faut ajouter le support de QGIS 3.16 et QGIS Master
