### ISSUE TITLE
Bug avec les algorithmes d'installation et de maj de la BDD

### ISSUE THREAD

**Issue by drillinP** [3liz/qgis-gestion_base_adresse-plugin#103]
Après réinstallation du plugin adresse, lors de l'utilisation des deux algo cités dans le titre j'ai cette erreur:  [`ModuleNotFoundError: No module named 'processing.gui.wrappers_postgis'`](https://github.com/3liz/qgis-gestion_base_adresse-plugin/blob/master/gestion_base_adresse/processing/structure/create_database_structure.py#L70-L76)

**Comment by Gustry** [comment]
Même soucis que #102 
C'est la migration à QGIS 3.16. Il faut reprendre PgMetadata.

**Comment by rldhont** [comment]
#66 a été mergé ce bug est corrigé
