### ISSUE TITLE
Ajouter test transaction

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#106]
* [x] Ajouter `Begin` et `Commit` à tous les fichiers SQL
* [x] Ajouter le test de vérification de `Begin` et `Commit` dans les fichiers SQL https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/blob/master/veloroutes_voies_vertes/test/test_migration_file.py#L20

**Comment by drillinP** [comment]
COmmit 6103051
