### ISSUE TITLE
Amélioration v_point_adresse

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#120]
Dans la vue `v_point_adresse` au lieu d'utiliser `st_Intersects`, il est préférable d'utiliser le fait que `id_com` est une clé étrangère vers `id_commune` de commune.

Il est aussi préférable d'utiliser le lien entre `commune` et `commune_deleguee` via `referencer_com` que d'utiliser `st_intersects`.

**Comment by drillinP** [comment]
Commit 43b4eb82fdc34ce347ee74c7f0d102468c3403ec

**Comment by drillinP** [comment]
Commit 43b4eb82fdc34ce347ee74c7f0d102468c3403ec
