### ISSUE TITLE
Simplifier la table lieu_dits et créer une vue v_lieu_dits éditable

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#121]
La table `lieu_dits` contient des champs inutiles:
* `commune_nom`
* `id_com_del`
* `commune_deleguee_nom`

La vue `v_lieu_dits` à l'aide des tables commune, `referencer_com` et `commune_deleguee` doit permettre de proposer le même contenue. Cette table devant être éditable de la même manière que `v_point_adresse`

**Comment by drillinP** [comment]
Commit d05092be7f06c08373726b582e97ae72c505adad
