### ISSUE TITLE
Champs cad_parcelles dans v_export_bal

### ISSUE THREAD

**Issue by drillinP** [3liz/qgis-gestion_base_adresse-plugin#134]
Pour l'export BAL dans le modèle actuel nous avons `cad_parcelles` qui est définis dans la vue `v_export_bal` et est égal l'idetifiant de la parcelle.  Définition de `cad_parcelles` suite à la réponse client: 
```
cad_parcelles (optionnel)
Les parcelles sont représentées par leur code, unique au niveau national. 
Ce code est de cette forme: code de département (2 caractères), code de direction (1 caractère), 
code de commune (3 caractères), préfixe de section (3 caractères), code de section (2 caractères), 
code de parcelle (4 caractères).
```

**Comment by rldhont** [comment]
J'ai modifié l'intitulé.

**Comment by drillinP** [comment]
J'ai modifié le commentaire de l'issue

**Comment by drillinP** [comment]
le champ `cad_parcelles` était configuré comme il faut, il fallait juste modifié le champ `id` de la tables `adresse.parcelle`.
Commit 887e78677ae6e47f69f0cb6ecb4da8a7f35014b3
