### ISSUE TITLE
Utiliser un UPSERT pour la mise à jour du contenu de la table parcelles

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#137]
Suite à #136 et pour améliorer les performances de l'algorithme d'Ajout des données parcellaires, il serait préférable d'utiliser un UPSERT pour mettre à jour le contenu de la tables parcelles.

C'est aussi l'occasion de modifier :
* la description de l'algorithme
* la récupération de l'identifiant de parcelle

L'identifiant de parcelle unique au niveau national est de la forme: code de département (2 caractères), code de direction (1 caractère), code de commune (3 caractères), préfixe de section (3 caractères), code de section (2 caractères), code de parcelle (4 caractères).

**Comment by drillinP** [comment]
Commit 887e78677ae6e47f69f0cb6ecb4da8a7f35014b3
