### ISSUE TITLE
Structure schema adresse incomplet

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#22]
Le 14 a remonté des bugs qui semble-t-il ont été corrigé.

La strcuture du schema adresse de leur base est là 
[db_schema_adresse_14.txt](https://github.com/3liz/qgis-gestion_base_adresse-plugin/files/4381844/db_schema_adresse_14.txt)

La structure a été mis à jour depuis la version 0.2.4 vers 0.2.6 à la main en executant le fichier d'upgrade 0.2.5 corrigé et en modifiant la table metadata

```sql
UPDATE adresse.metadata
SET (me_version, me_version_date)
= ( '0.2.5', now()::timestamp(0) );
```

**Comment by drillinP** [comment]
[schema_bdd.txt](https://github.com/3liz/qgis-gestion_base_adresse-plugin/files/4408373/schema_bdd.txt)

**Comment by mdouchin** [comment]
Différences constatées suite à import des 2 fichiers joints dans nouvelle bdd et export:
* table `adresse.point_adresse` : dans la version de @drillinP la table a un champ en plus: `validation boolean DEFAULT false`

Il y a d'autres différences liées à l'export BAL (nouvelle vue et modification du tableau bis, ter), mais qui sont normales car le fichier de @drillinP provient d'une version avec cette fonctionnalité en plus

**Comment by drillinP** [comment]
donc si il n'y a que le champ validation comme différence autre que l'export bal il devrait n'y avoir aucun problème

**Comment by rldhont** [comment]
Il faut donc ajouter `validation boolean DEFAULT false` au fichier d'upadate si ce n'est pas déjà fait.

**Comment by rldhont** [comment]
@drillinP d'après https://github.com/3liz/qgis-gestion_base_adresse-plugin/commit/9db694733e2b00d18f9fe321aac8192b4b139c29 la table `adresse.point_adresse` contient bien `validation boolean DEFAULT false`, peux-tu le confirmer et fermer cette demande

**Comment by drillinP** [comment]
il manque le alter table dans le fichier d'upgrade pour le champs validation. je le met dans la prochaine version ?

**Comment by rldhont** [comment]
Oui, merci

**Comment by drillinP** [comment]
Champ ajouté dans le PR "Fix bugs" du plugin
