### ISSUE TITLE
Modifier la description et l'alias du champs adresse.voie.sens

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#25]
Le commentaire du champ `adresse.voie.sens` ne correspond pas exactement à l'utilisation qui en est faîtes:
```sql
-- voie.sens
COMMENT ON COLUMN adresse.voie.sens IS 'Stocke l’information si la voie à été changé de sens';
```

Il en est de même pour l'alias QGIS :
```xml
<alias name="Inverser le sens ?" index="7" field="sens"/>
```

Le champ `adresse.voie.sens` est utilisé pour savoir si les nombres pairs sont à droites ou à gauche de la voie par rapport au sens de dessin. Il faut donc modifier ces 2 informations pour que l'utilisation de ce champs soit bien clair.

**Comment by drillinP** [comment]
je m'en charge
