### ISSUE TITLE
Bug: calcul du numéro d'adresse en métrique

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#27]
Cette ligne est fausse car elle n'utilise pas la longueur de la ligne mais la longueur entre le point de départ de la ligne et le point sur la ligne.
```
SELECT ST_Length(ST_MakeLine(ST_StartPoint(v.geom), ST_ClosestPoint(v.geom, pgeom)))::integer into num
```

Elle devrait être 
```
SELECT round(ST_Length(v.geom)*ST_LineLocatePoint(v.geom, pgeom))::integer into num
```
Car elle utilise la longueur de la voie complète.

**Comment by drillinP** [comment]
En fait je créer une ligne  qui part du debut de la voie jusqu’au point le plus proche du point de l'adresse sur la voie. puis je prend la longueur de cette ligne

**Comment by drillinP** [comment]
après test t'as version parait plus juste

**Comment by rldhont** [comment]
As-tu fait la modification dans le code ?
