### ISSUE TITLE
[Test] Calcul du numéro d'adresse : Ajouter 2 et 2bis puis tester que le système propose bien 4

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#28]
Si il existe déjà un 2bis et 2ter la méthode renvois un 2ter ou 2quater au lieu de 4.

**Comment by drillinP** [comment]
le problème viens du fait qu'il est plusieurs voie en mode déverrouillées. pourtant dans le code on va chercher la voie déverrouillée la plus proche. Mais la je remarque que si il y a plusieurs vois déverrouillées alors elles provoques les bugs rencontrés.

**Comment by drillinP** [comment]
@rldhont j'ai trouvé je crois qu'il n'y a pas de bug mais une mauvaise manipulation, peuton s'appeller cet après midi ?

**Comment by rldhont** [comment]
@drillinP peux-tu ajouter le test suivant ?
1. Ajout d'un premier point, avec le 2
2. Ajout d'un second pint, avec le 2 bis
3. Test d'ajout d'un troisième point, test d'égalité à 4

**Comment by drillinP** [comment]
Comment le test, dans la fonction sql ?

**Comment by rldhont** [comment]
Ajouter un test pour vérifier.

**Comment by rldhont** [comment]
@drillinP Peux-tu préciser quel code corriger ce bug ?

As-tu créer le test que je t'ai demandé ?
