### ISSUE TITLE
Créer des indexes sur les clés étrangères

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#3]
Pour une meilleure performance, ajouter la création des indexes sur les clés étrangères.

**Comment by rldhont** [comment]
@drillinP Peux-tu ajouter les indexes sur les champs ayant des contraintes de clés étrangères avant la prochaine version ?

**Comment by drillinP** [comment]
https://github.com/3liz/qgis-gestion_base_adresse-plugin/commit/c75ec687a5efd90a8a89b875e8c81f04315948f0
