### ISSUE TITLE
[Test] Ajouter des tests sur les champs des tables

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#31]
Afin de s'assurer que les fichiers d'upgrade contiennent bien les modification des tables, il serait intéressant d'avoir des tests sur les liste des champs des tables.

**Comment by Gustry** [comment]
> Il serait intéressant d'avoir des tests sur les liste des champs des tables.

Ce n'est pas suffisant ! Wait for it ;-)

**Comment by Gustry** [comment]
Dans #34 , Travis permet de détecter une différence entre une installation fraîche et les migrations sur
FUNCTION
TABLE|SEQUENCE|DEFAULT
VIEW
INDEX
TRIGGER
CONSTRAINT
COMMENT
