### ISSUE TITLE
[Test] Inversion sur numérotation métrique

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#35]
Il faudrait tester la numérotation métrique après inversion d'une voie afin de s'assurer du fonctionnement de la numérotation avant et après inversion.

**Comment by rldhont** [comment]
@drillinP Peux-tu préciser quel code corriger ce bug ?

**Comment by drillinP** [comment]
Pour moi ca marche donc aucun code de correction n'a été apporté

**Comment by rldhont** [comment]
Peux-tu faire un test avec : 
* 4 points d'adresse à différents endroits de la voie à droite et à gauche -> test de la numérotation sans ajout dans la base
* Inversion de la voie
* teste de la numérotation avec les mêmes points sans ajout dans la base
