### ISSUE TITLE
Le champ "id_commune" de la table "point_adresse" est vide après INSERT

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#37]
Il faudrait tester un INSERT et vérifier le résultat afin de tester les triggers.

**Comment by rldhont** [comment]
@drillinP Peux-tu préiser quel code corriger ce bug ?

**Comment by drillinP** [comment]
@rldhont je n'ai pas ce problème cela fonctionne très bien

**Comment by rldhont** [comment]
@drillinP peux

**Comment by rldhont** [comment]
@drillinP peux-tu créer un test pour s'assurer que l'id_commune est correctement préciser ?

**Comment by rldhont** [comment]
@drillinP as-tu créé un test ?

**Comment by rldhont** [comment]
Le test est là https://github.com/3liz/qgis-gestion_base_adresse-plugin/blob/master/gestion_base_adresse/test/test_execute_functions.py#L422
