### ISSUE TITLE
Ajouter des commentaires sur les champs des tables

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#4]
Pour une meilleure description des données, ajouter des commenatries au champs des tables.

**Comment by rldhont** [comment]
@drillinP Peux-tu ajouter les commentaires sur la structure des tables avant la prochaine version ?

**Comment by Gustry** [comment]
Il faut aussi regénérer la doc schemaspy. C'est dans le dossier `scripts/`.

**Comment by drillinP** [comment]
https://github.com/3liz/qgis-gestion_base_adresse-plugin/commit/c75ec687a5efd90a8a89b875e8c81f04315948f0
