### ISSUE TITLE
Modifier la fonction calcul_num_adr

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#45]
Modifier la fonction `calcul_num_adr` à partir de la ligne 35 https://github.com/3liz/qgis-gestion_base_adresse-plugin/blob/master/gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql#L35
```
    -- Get idvoie
    SELECT id_voie into idvoie
    FROM( SELECT id_voie, ST_Distance(pgeom, geom) as dist
    FROM adresse.voie
    WHERE statut_voie_num IS FALSE ORDER BY dist LIMIT 1) AS d;

    SELECT adresse.calcul_point_position(adresse.calcul_segment_proche(geom, pgeom),pgeom)into isleft
    FROM( SELECT geom, id_voie, ST_Distance(pgeom, geom) as dist
    FROM adresse.voie
    WHERE statut_voie_num IS FALSE AND id_voie=idvoie ORDER BY dist LIMIT 1) AS d;
```

**Comment by drillinP** [comment]
Il faut inverser les deux blocs de code ? @rldhont

**Comment by rldhont** [comment]
@drillinP oui et utiliser le `idvoie` dans la requête définissant `isleft`

D'ailleurs il faut modifier la requête `isleft` plus besoin de `limit 1`
