### ISSUE TITLE
AJouter un test pour calcul_segment_proche

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#49]
Il faudrait pouvoir tester la fonction calcul_segment_proche. Ce test n'a pas besoin de s'appuyer sur des géométries en bases de données.

**Comment by Gustry** [comment]
Vous voulez une base vide de données de test?

**Comment by rldhont** [comment]
Pas besoin, mais le test n'a pas besoin d'utiliser de données en base juste de fausse géométrie WKT.

**Comment by drillinP** [comment]
d'accord

**Comment by Gustry** [comment]
Si vraiment vous n'avez pas besoin des données en base, juste la structure, je vous conseille #51

**Comment by drillinP** [comment]
@gustry ton PR ajoute le fait de pouvoir faire des tests avec un base de données vide ?

**Comment by Gustry** [comment]
oui, juste la structure.
Tu peux remplacer ma fonction que j'ai ajouté

**Comment by Gustry** [comment]
Cela permet de gagner quelques secondes quand on lance les tests chez nous, pour éviter de charger des données inutiles lors de chaque test.

**Comment by rldhont** [comment]
Fait https://github.com/3liz/qgis-gestion_base_adresse-plugin/pull/59
