### ISSUE TITLE
[Demo] Corriger le champs id_voie du formulaire point_adressse

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#55]
Sur la démo https://demo.lizmap.com/adresse/index.php/view/map/?repository=demo&project=adresse, le Widget de saisie du champs id_voie est mal configuré.

Il est impossible pour l'utilisateur de connaître la voie à laquelle va être associé le point_adresse.

Il faut vérifier que le widget de saisie du champs id_voie est bien configuré dans les fichiers qpt fourni apr le plugin.

**Comment by drillinP** [comment]
@rldhont modification faite
