### ISSUE TITLE
Suppression de voie impossible même si plus aucun point d'adresse

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#62]
Il n'est pas possible de supprimer une voie après avoir supprimer tous les points adresses.

Pour bien faire, il faut appliquer la méthode suivante

- [x] Créer un test : Ajouter une voie et la supprimer - la voie n'est plus en base
- [x] Créer un test : Ajouter une voie, la dévérouiller et la supprimer - la voie n'est plus en base
- [x] Créer un test : Ajouter une voie, la dévérouiller, y ajouter des points adresses et la supprimer - la voie est toujour en base
- [x] Créer un test : Ajouter une voie, la dévérouiller, y ajouter des points adresses, supprimer les points adresses et la supprimer - la voie n'est plus en base

**Comment by drillinP** [comment]
Je sais d'où viens le problème, on moment de la suppression il faut aussi supprimer le/les enregistrements correspondants dans la table intermédiaire entre les voies et les communes

**Comment by drillinP** [comment]
J'ajouterais les tests, mais pour résoudre le bug il faut en js que j'ajoute a l'event suppression de supprimer les enregistrements de la table intermédiaires @rldhont ?

**Comment by rldhont** [comment]
En cours https://github.com/3liz/qgis-gestion_base_adresse-plugin/pull/63
