### ISSUE TITLE
Choisir le CRS à utiliser dans le modèle de données

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#81]
Pour le moment le modèle de données est créé avec le CRS `EPSG:2154`.

Pour les DOM mais aussi ceux qui souhaitent utiliser les CRS `RGF93 / CC**`, ils doivent pouvoir préciser le CRS à la création de la base de données.

**Comment by drillinP** [comment]
Commit d53051bfbaf80439e90435ee4935946f0bcafc5b
