### ISSUE TITLE
Support Dev

### ISSUE THREAD

**Issue by drillinP** [3liz/qgis-gestion_base_adresse-plugin#85]
* Concernant la délibération Est-il intégré ?
* Ajouter également au correctif toutes les voies géographiquement situées sur la commune pour delib
* Dans l'export SNA, nous souhaiterions que soit intégré la délibération que nous aurons au préalable ajouter via la gestion documentaire.
* La case à cocher "Dernière délibération" dans la fenêtre des exports. A quoi cela correspond-il ?
* Dans l'export BAL, il reste une dernière information à compléter : le champ source.
Il faudrait qu'il soit complété par le nom de la commune

**Comment by drillinP** [comment]
@rldhont  Pour chaque point évoquer tout est déjà dans le module. Je refais des tests au cas ou, mais tout marchais comme il faut.

**Comment by rldhont** [comment]
@drillinP ok, je dois faire une mise à jour du module.

**Comment by drillinP** [comment]
@rldhont  Concernant la case à cocher il s'agit du fait ou l'on veut uniquement la dernière délibération ou toutes les délibération pour l'export SNA

**Comment by rldhont** [comment]
@drillinP est-ce dans la documentation ?

**Comment by drillinP** [comment]
@rldhont non, je l'ajoute

**Comment by Gustry** [comment]
https://docs.3liz.org/qgis-gestion_base_adresse-plugin/module-lizmap/user-guide/#export-de-document
Dans la documentation, je peux lire 

> Sur l'image du minidock ci-dessus on aperçoit une case à cocher Dernière délibération . Cela signifie que l'on a la possibilité, dans l'export SNA, d'y intégrer soit la dernière délibération soit toutes les délibérations de la commune.

Peut-être que l'on peut fermer ce ticket désormais ?

**Comment by rldhont** [comment]
Je clos
