### ISSUE TITLE
Modification de l'algorithme data_parcelle

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-gestion_base_adresse-plugin#87]
- [x] Ajouter un paramètre TRUNCATE_PARCELLE / Mise à jour du contenu de la table parcelle / booleen, si vrai
  - [ ] `SET id_parcelle = NULL` pour `adresse.point_adresse`
  - [ ] `TRUNCATE adresse.parcelle RESTART IDENTITY`
  - [ ] `INSERT INTO adresse.parcelle` 
  - [ ] `SET id_parcelle WHERE st_intersects` pour `adresse.point_adresse`
- [x] Modifier les requêtes de création des vues en ajoutant `OR UPDATE` ou bien vérifier que les vues existent déjà
- [x] Modifier le nom des vues en remplaçant `vue_` par `v_`

**Comment by drillinP** [comment]
@rldhont le `TRUNCATE adresse.parcelle RESTART IDENTITY` pose problème car il a une références de d'id avec point_adresse donc postgres dit de `TRUNCATE ... CASCADE` sauf que en `CASCADE` cela vide aussi point_adresse meme si le champ de référence est null

**Comment by drillinP** [comment]
Pour le moment la seule solution que j'ai en te c'est de supprimer la table et la recréer

**Comment by drillinP** [comment]
Une solution: 
  * Supprimer la contrainte de clé étrangère
  * Vider la table parcelle
  * Recréer la contrainte
